---
- name: System Configuration & Dotfiles Provisioning
  hosts: localhost
  connection: local
  vars:
    dotfiles_dir: "{{ ansible_facts['env']['HOME'] }}/dotfiles"
    user_name: "{{ ansible_facts['user_id'] }}"
    stow_packages:
      - bin
      - dunst
      - eww
      - fuzzel
      - fuzzel-hyprpicker
      - hypr
      - kitty
      - kmonad
      - nvim
      - systemd
      - yazi
      - zsh

  tasks:
    - name: Configure passwordless Wi-Fi switching and pacman execution
      become: true
      ansible.builtin.copy:
        dest: /etc/sudoers.d/10-ansible-permissions
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s
        content: |
          {{ user_name }} ALL=(ALL) NOPASSWD: /usr/bin/ip link set * down, /usr/bin/ip link set * up, /usr/bin/iw dev * set type *, /usr/bin/systemctl start iwd, /usr/bin/systemctl stop iwd, /usr/bin/pacman

    - name: Ensure base official runtime dependencies are installed
      become: true
      community.general.pacman:
        name:
          - stow
          - dkms
          - linux-headers
          - iwd
          - wireless_tools
          - dunst
          - jq
        state: present

    - name: Ensure AUR dependencies are installed
      kewlfft.aur.aur:
        name: python-sdbus
        use: yay
        state: present

    - name: Run GNU Stow for user configuration packages
      ansible.builtin.command:
        cmd: "stow -R -d {{ dotfiles_dir }} -t {{ ansible_facts['env']['HOME'] }} {{ item }}"
      loop: "{{ stow_packages }}"
      changed_when: true

    - name: Reload systemd user daemon
      ansible.builtin.systemd:
        scope: user
        daemon_reload: true

    - name: Enable and start wayinfo / info_daemon user service
      ansible.builtin.systemd:
        scope: user
        name: info_daemon.service
        enabled: true
        state: started
